### ISSUE TITLE
Version v1beta1 of this API is no longer available. Please try again using JSON API v1

### ISSUE THREAD

**Issue by Aricg** [GoogleCloudPlatform/storage-metabucket-javascript#2]
I've followed the instructions, and put my api key and bucket in js/metabucket.config.js 
as well as setting a cors file.

The page works, but the contents never load.
This is the response I'm getting.

{ "error": { "errors": [ { "domain": "global", "reason": "turnedDown", "message": "Version v1beta1 of this API is no longer available. Please try again using JSON API v1. To request temporary reinstatement for your project, please visit <CUT>

after changing the api url, the bucket loads, but the file names are a string of numbers.

**Comment by jterrace** [comment]
Fixed with 8dc8a603e7f8eb3b12d7b53d5447c35761db6b96
